default: &default
  adapter: mysql2
  pool: 5
  encoding: utf8
  database: "<%= ENV['DB_NAME'] %>"
  host: "<%= ENV['DB_HOSTNAME'] %>"
  port: "<%= ENV['DB_PORT'] %>"
  username: "<%= ENV['DB_USERNAME'] %>"
  password: "<%= ENV['DB_PASSWORD'] %>"

development:
  <<: *default
 
staging:
  <<: *default
  
production:
  <<: *default
